Traceback (most recent call last):
  File "Reinigen.py", line 324, in <module>
  File "Tkinter.pyc", line 1728, in destroy
_tkinter.TclError: can't invoke "destroy" command:  application has been destroyed
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1410, in __call__
  File "Reinigen.py", line 38, in choose_folder
  File "Reinigen.py", line 263, in createWindow
  File "files.pyc", line 51, in traverse
WindowsError: [Error 5] Access is denied: u'C:/\\Config.Msi\\*.*'
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1410, in __call__
  File "Reinigen.py", line 38, in choose_folder
  File "Reinigen.py", line 263, in createWindow
  File "files.pyc", line 51, in traverse
WindowsError: [Error 5] Access is denied: u'C:/\\Config.Msi\\*.*'
